server:
  port: 8888
spring:
  application:
    name: blog-backed
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    expire: 60000 # 自定义属性
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  mapper-locations: classpath:com/cmc/mapper/xml/*.xml
  type-aliases-package: com.cmc.entity
  # configuration:
  #   map-underscore-to-camel-case: false

logging:
  level:
    com.manong.dao: debug

# 自定义属性相关配置
request:
  login:
    url: /user/login

jwt:
  secret: XiaoHeMiaoYa
  expiration: 604800000

# 阿里云 OSS 配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyId: ${ALIYUN_KEYID}
      keySecret: ${ALIYUN_KEYSECRET}
      bucketName: cmc-blog
      region: cn-hangzhou

token:
  prefix: token

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-producer-group
  consumer:
    group: my-producer-group

myBlog:
  column:
    defaultCoverImg: https://cmc-blog.oss-cn-hangzhou.aliyuncs.com/articleImg/25dd157c-c944-47b8-b2db-ac58e04d95f8_xiaohemiao.jpg